### PR TITLE
Remove try catch since 俺の同僚がいらないと言った

### PR DESCRIPTION
**Pull request by satour8**
トラー　キャッチ　が　いらない
SINCE　IT　WILL　いつでも　成功

### CODE REVIEW

**Comment by ShiriNmi1520** [comment]
I think maybe we can give your coworker a lesson that we should always expect the unexpected cause you will never know when it not working

**Comment by satour8** [comment]
Sure let’s get him a wheelchair

**Comment by satour8** [comment]
Until he's remember to close door when leaving ♿

**Comment by ShiriNmi1520** [comment]
LOL let's wait till that day come

**Comment by ShiriNmi1520** [comment]
@thootau99 Thanks for your contribution, but I think your pull request deserves a new branch instead of merge it into master, I'll take care of this later

**Comment by ShiriNmi1520** [comment]
@thootau99 I'll move your pull request from master branch to no_error_handling branch :)

**Pull request merged**
